### ISSUE TITLE
how can you access a player object class without accessing the whole group

### ISSUE THREAD

**Issue by lewislepton** [varomix/khatmx#4]
hey man,

just trying to work thru this, but im trying to access a player either with as object group or whatever. but am having some trouble getting this to work. just looking to really use tiled as my primary level building suite and use kha. but getting no where right now.
but that would mean using it to position players and the such. doing in tiled is fine, but its then controlling from kha thats proving the problem

uploaded a level im just playing with. but the access points are a bit confusing to say the least.

cheers

[Archive.zip](https://github.com/varomix/khatmx/files/602116/Archive.zip)

**Comment by lewislepton** [comment]
actually did just spot your branch ninja project that uses tmx. ill have a look at that, but any pointers would be good

**Comment by varomix** [comment]
Hey

yeah check what I did for Branch Ninja, the thing is, I didn't set the player on Tiled but you could access it by using map.getObjectGroupByName("player")
and put that in a variable to control it
hope that helps

**Comment by lewislepton** [comment]
aye. seems that branch ninja does have quite a bit to dive into. cheers man

**Comment by lewislepton** [comment]
hey man. rathr than reopening. i just thought id post. but did try a few things. but still unable to get things moving tried a few things but just running dry. im trying without kha2d by the way, but still being weird and a bit confusing
this was the latest iteration. see if you can see what is going on

[TILEPLAYER.zip](https://github.com/varomix/khatmx/files/612243/TILEPLAYER.zip)

**Comment by varomix** [comment]
Ok here it is
basically I created a layer for the player, or you can have it in the same layer as the collision is up to you
the thing is, first EXTRACT the tiled object then from that create your player object
also give a NAME to the object itself in Tiled, by selecting it and in the properties typing a name
hope is clear in the file

[TILEPLAYER.zip](https://github.com/varomix/khatmx/files/612301/TILEPLAYER.zip)

**Comment by lewislepton** [comment]
ah ha. ok. i see.
many thanks for that, it was just getting cofusing.
but many thanks man. many many thanks

**Comment by varomix** [comment]
glad to help man
